version = 0.1
[default.deploy.parameters]
stack_name = "samreuse"
resolve_s3 = true
s3_prefix = "samreuse"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
parameter_overrides = "CPUThreshold=\"20\" EC2InstanceId=\"i-0d7bde0b91bc5c160\""
